### ISSUE TITLE
Is it possible to hack lobby names?

### ISSUE THREAD

**Issue by GitHubWhatsup** [music-discussion/TownOfHost-TheOtherRoles#101]
Innersloth updated the game, so now every public lobby name is randomized.
It's so hard to find a modded lobby now.
Is it possible to hack the game to indicate people they are modded lobbies?
For example:
By adding TOR to lobby names or changing the color of lobby names?
Or by hacking maximum players to a different numbers than 15, like 16?

**Comment by music-discussion** [comment]
no.
