### ISSUE TITLE
Role question: Ninja

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-TheOtherRoles#13]
(Sorry for spelling mistakes if any)

Yesterday, the version of "TOH-TOR 7a" was released, and before the release, I suggested the role of "Ninja" and you wrote that you added this role and closed the issue, but in the settings in the list of roles cannot enable the role of "Ninja", since this role is not in general in settings

Perhaps this role will appear in the full version of v7, but I think this is a bug and therefore opened the question

**Comment by music-discussion** [comment]
nah 0.7a does not have Ninja. the real version of 0.7 will tho
