### ISSUE TITLE
i dont have an issue just a Q

### ISSUE THREAD

**Issue by babavosgal** [music-discussion/TownOfHost-TheOtherRoles#130]
I just want to know is there a way to automatically ban/kick people who say start? and how to change my name color in game, like with the cool text above my name. thanks, didnt know who to ask.

**Comment by ThetaHalo** [comment]
Auto-Kick for saying start is supposed to be coming in 0.9.3.5, and for the cool text above your name you do /tag create static (yourfriendcode.1234) (hex color you want but with no #) and (thing above your name)

**Comment by babavosgal** [comment]
okkk thanks! Just checking do i put this in template? or somewhere else? and is this right:
/tag create static(hehohah.9390)(CBDFBB)(workplease)

**Comment by babavosgal** [comment]
@Gurge44 thank you heaps I finally got it to work! 👯
