### ISSUE TITLE
Banned from my own lobby

### ISSUE THREAD

**Issue by BC1981** [music-discussion/TownOfHost-TheOtherRoles#136]
A ton of disconnects.  Then banned when I hit start.

**Comment by Gurge44** [comment]
1) if your disconnect message is "sent 6 ping that remote did not respond to", blame innersloth for their bad servers.
2) "you got kicked from the lobby" as host after the game started, there is most likely an issue with a pet role. Make sure your players all have a pet equpped before starting.
3) Make sure you don't have any fortegreen colored players in your lobby (this will prevent starting a game)
4) Sometimes a shapeshifting role causes an error which results in the host getting banned. + Don't shapeshift too early after a meeting (wait 20-30 seconds) or the anti-cheat will kick/ban you (blame innersloth).
5) There has been many issues with the North Amerca server, try using Europe or Asia instead.
6) if your disconnect message is "reliable packet size 7529 was not ack'd after 6382 ms (9 resends)" or something similar, try using a VPN.
