### ISSUE TITLE
Chat spammed with periods during meetings

### ISSUE THREAD

**Issue by depperoni** [music-discussion/TownOfHost-TheOtherRoles#144]
This does not happen when I host vanilla, but recently when I host TOHTOR the chat instantly gets spammed with a lot of messages containing periods. Like this:
.
.
.
.
.
.
.
.
.
.
.
.
.

The mod eventually blocks the command but it just happens again in the next meeting. Photo attached.
![image0](https://user-images.githubusercontent.com/116839424/213616121-c24ef040-6e26-40fb-93c9-87fc28588e95.jpeg)

**Comment by Gurge44** [comment]
Turn off "Hide Command" under Assassin settings.
