### ISSUE TITLE
The Glitch can't shapeshift

### ISSUE THREAD

**Issue by JonMonky** [music-discussion/TownOfHost-TheOtherRoles#145]
for some reason, whenever im hosting a town of host the other roles lobby, and i get 'The Glitch' role, i can't shapeshift... this is only happening for me, and i think others who have the mod. but when i was joining someone elses lobby, and i got 'The Glitch' i was able to shapeshift, and also i can't vent as the glitch for some reason...

**Comment by Jes-debug** [comment]
smh for modded clients they use pet button instead of shapeshift button
