### ISSUE TITLE
Can u guys unban me on ur discord please?

### ISSUE THREAD

**Issue by xprogamer008** [music-discussion/TownOfHost-TheOtherRoles#151]
To the Admins at TOHTOR discord, please can u guys unban me i mean a guys said to make a ticket so i ban apply but i can't because i am banned. i lied about being 12 i am 14 born on 4th of August 2008. i just wanna play with people TOHTOR. is that to much to ask?

**Comment by Jes-debug** [comment]
:skull:
average discord kid getting ban for being underage

**Comment by Gurge44** [comment]
bruh, that grammar instantly exposes your age lol
