### ISSUE TITLE
Can't Open the Mod

### ISSUE THREAD

**Issue by Blykey** [music-discussion/TownOfHost-TheOtherRoles#155]
Always when opening the Mod this screen pops up And idk how to Play ToH-ToR now please help
![image](https://user-images.githubusercontent.com/126958113/225713692-36ea0934-c308-4522-aaf2-20cec71dc2a0.png)

**Comment by music-discussion** [comment]
Please make sure your among us is up to date, and you are on the latest version of the mod.
