### ISSUE TITLE
Black Screen on The Airship map

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-TheOtherRoles#16]
Lobby host has a black screen after meeting on The Airship map

Video demonstrating the problem:
https://drive.google.com/file/d/1C0n9Iy_eSdjuCcpv-4vgciuMGfXc6rmY/view?usp=sharing

The rest of the players are playing normally

**Comment by music-discussion** [comment]
Yea. I have seen this. Airship is broken with this mod. To be fair, Airship is a trash map. /j
I will not be fixing this right now as I have no idea what causes it.
If you have more info, I may look into it.

**Comment by Tommy-XL** [comment]
It's a pity :(
To be honest, it seems to me that this arises from some kind of role, because it didn’t happen before, or perhaps in the game code you touched or interacted with the code of this card because of this, this bug happens
