### ISSUE TITLE
Suggestion: Game does not proceed when only Plaguebearer is alive

### ISSUE THREAD

**Issue by Gurge44** [music-discussion/TownOfHost-TheOtherRoles#17]
My suggestion would be that when all killers are dead / voted out, and only the Plaguebearer is alive, the game should end with the Plaguebearer losing. Similar to Arsonist. The reason is that the Plaguebearer cannot kill until they infect everyone and become the Pestilence, and without kills, the game is pretty dull. The Pestilence is a different role, of course, the game would not end if there is a Pestilence alive, since they can kill. At least please make a setting available for whether the Plaguebearer causes the game to continue when they're the only potential killer alive or not.
And one other setting could be for a situation like when there are 3 players left, one is a crewmate, one is the Plaguebearer, and one is a different neutral killer. So, if the one crewmate is voted out, does the "one different neutral killer" instantly win, or does the Plaguebearer get a chance to infect them and become Pestilence?
There would be my 2 suggestions, either as game mechanics changes or game settings. Hopefully, I explained everything well and you understood.

**Comment by music-discussion** [comment]
Yes, any nk keeps game going no matter what. If 2 nks are the last players alive, they do a 1v1 or battle it out or something. If I may ask, why don't you want plaguebearer to keep game going?

**Comment by music-discussion** [comment]
Arsonist in new update keeps game going. . .
