### ISSUE TITLE
Role Suggestion: Insomniac

### ISSUE THREAD

**Issue by Jaytan804** [music-discussion/TownOfHost-TheOtherRoles#19]
Team: Crewmates
Basis: Crewmate
Inspired by Ultimate Werewolf

If someone uses a role-specific ability within the Insomniac's field of vision, the Insomniac will see an exclamation mark icon appear next to their name. Unlike the Veteran, the Insomniac can detect non-killing abilities (e.g. an Arsonist douse), as well as abilities that didn't target them or don't require a target (e.g. placing fireworks). However, the Insomniac isn't told who used the ability or what kind of ability was used. In addition, the exclamation mark icon doesn't disappear until the end of the next meeting, meaning that the Insomniac can only detect one ability use per round. The Insomniac is designed to prevent Impostors and Neutrals from claiming to be a vanilla Crewmate by default, encouraging more elaborate (and easier to call out) fake role claims.

**Comment by music-discussion** [comment]
some of those are pretty obvious tho, such as Fireworks. You have to shift to plant, so wouldn't you have already seen the bubble for it? Others make sense though.
As for coding, tracking every possible player movement is going to be hell.
