### ISSUE TITLE
Role Idea: Bomber

### ISSUE THREAD

**Issue by Gurge44** [music-discussion/TownOfHost-TheOtherRoles#21]
# **Bomber**

(This role is a combination of _Warlock_, _Vampire_, _Arsonist_, and _Puppeteer_, so it shouldn't be hard to code, at least I hope so :-))

The Bomber is an Impostor who can plant a bomb on other players just like a douse (has a douse time, not instant with just a click). After a set amount of delay, the Bombed player will kill the next person that shows up closest to them (within kill distance) with a lunge (kill teleport). As they make the kill, the bombed player gets roleblocked (for x amount of seconds) so they can't instantly report the body they just killed. (Bonus mechanic: Bomber gets stuck in place and cannot move after the bombed player has forcibly killed for x amounts of seconds (like trapper kills)). The Bombed player will have a symbol next to their name (eg. Arsonist triangle or smh) once the Bomber has planted a bomb on them which every other impostor can see (or when a setting states so). If a meeting gets called before the Bombed player's delay before the kill is over, the bombed player will die when the session is called (or when settings say so). Bonus mechanic: The Bomber can switch killing modes by entering a vent, killing modes would be planting a bomb or a normal kill. Their cooldown after planting a bomb should be higher than after a normal kill.
The Bomber does not get the "Last Impostor Kill Cooldown" bonus, even when they're the last killer left.
The Bomber can be roleblocked which prevents both killing modes.
When The Bomber plants a bomb on a neutral killer, you can have an option for whether if the neutral killer kills the Bomber after the Bomber planted a bomb on them, does the Bomb process still go through or not?

### **Settings:**

- **Bomber can Vent** (Yes/No)
- **Bomb Planting Duration** (like the arsonist douse time) (default: 3 seconds, 1-10s)
- **Bomb Plant Cooldown after planting a Bomb** (default: 60 seconds, 10-120s)
- **Bomb Plant Cooldown after a Regular kill** (default: 30 seconds, 10-120s)
- **Kill cooldown after planting a Bomb** (default: 40 seconds, 10-120s)
- **Bombed Player Kill Delay** (default: 5 seconds, 1-10s)
- **Bomber Can Switch kill modes via vent** (Yes/No)
- **Other impostors see the bombed player** (Yes/No)
- **The bombed player can kill other impostors when their kill is forced** (Yes/No)
- **The bombed player can kill the Bomber when their kill is forced** (Yes/No)
- **Bomber cannot move after the bombed player kills** (default: 0s (==off), 0-10s)
- **Role blocking the Bombed player blocks their forced kill** (Yes/No)
- **Doctors can see a separate kill type for bombed forced kills** (Yes/No)
- **Meeting call saves the Bombed player from the forced kill** (Yes/No) (No==Bombed player dies when the meeting is called)

(You don't have to add every feature or setting, these are just ideas :-))

**Comment by music-discussion** [comment]
A very complex role to say the least. When I am done with everything I have planned currently, I will get back to you.

**Comment by Gurge44** [comment]
Will this ever be added, or do I close this as "not planned"??

**Comment by music-discussion** [comment]
Hold on

**Comment by Gurge44** [comment]
Just to be clear, I don't mind if you release v0.8.4b without this role (and actually, I want you to release v0.8.4b as soon as possible), I just asked because someone else suggested nearly this same role :-D

**Comment by Gurge44** [comment]
Thank you for adding it :)
After 6 months, it's finally in. Thank you a lot.
