### ISSUE TITLE
Guesser Roles don't seem to be in the game although they are listed as "current roles"

### ISSUE THREAD

**Issue by P0W3R-0UT4GE** [music-discussion/TownOfHost-TheOtherRoles#22]

**Comment by music-discussion** [comment]
They are in the game. Just not in the current public version. In the next version, you will see guessing roles.

**Comment by P0W3R-0UT4GE** [comment]
Thank you! I sent you a friend request on discord to ask you a couple of questions. Do you have any idea when the next version will release?

**Comment by music-discussion** [comment]
I don't currently have an ETA. I keep getting new ideas.
