### ISSUE TITLE
Message box disappearing

### ISSUE THREAD

**Issue by The-LaughingMan** [music-discussion/TownOfHost-TheOtherRoles#23]
My message box during a meeting disappears when either A) A Timelords kills reduces meeting time, or B) when i have the map open at the time a meeting or body is reported.

Both instances of that happening have removed my message box from a meeting. Meaning the message icon, to open chat during a meeting, is gone.  Basically not letting me talk during a meeting.  It also wont let me skip, i have to either vote or wait for the timer to expire.
I was the host of this mod on every instance of this happening.

**Comment by music-discussion** [comment]
This bug has been acknowledged and I am working on fixing it.

**Comment by The-LaughingMan** [comment]
Thanks! I use your  mod often and I will try my best to report any unusual bugs that I cannot figure out how to fix myself. Every time im with a new group i always ask for their feedback on a new role thats being used.  Most often its just a mobile user that has the issues and im assuming it happens because..well..they are on mobile :P but this one was a special case cause it only happened to the host.
