### ISSUE TITLE
Question about Witch

### ISSUE THREAD

**Issue by McNnane** [music-discussion/TownOfHost-TheOtherRoles#24]
Is there any intention to make it so that instead of having to kill to curse, witch would be able to choose between cursing or killing by choice? Incase that doesn’t make sense, witch being able to choose to only use spells in a round for multiple curses in a meeting instead of being forced to swap between the two.

**Comment by SkullCreeper** [comment]
While there is no intention for that at the moment, I'd like to see this as I dislike Witch for this very reason.

**Comment by music-discussion** [comment]
May do something like Warlock. Curse people in meetings while not shifted, and kill while shifted.

**Comment by McNnane** [comment]
> May do something like Warlock. Curse people in meetings while not shifted, and kill while shifted.

Just realized you meant you’d have one option while shifted and the other while not shifted, I originally thought you meant curses would die when you shifted and I was confused. Mb

**Comment by music-discussion** [comment]
will have this as an option for Witch
