### ISSUE TITLE
Arsonist/veteran bug?

### ISSUE THREAD

**Issue by Dewi03** [music-discussion/TownOfHost-TheOtherRoles#25]
I don't know if this is supposed to happen, but when arsonist tries to douse the veteran when they're on watch, the arsonist dies.

**Comment by SkullCreeper** [comment]
When the Veteran is on alert, **all** interactions on the Veteran cause the Veteran to kill the source. Arsonist dousing (and Plaguebearer infecting) will cause the Veteran to kill them.
Veteran killing crew can be turned off but that ruins the fun.

**Comment by music-discussion** [comment]
true.
