### ISSUE TITLE
career bug

### ISSUE THREAD

**Issue by MC-AS-Huier** [music-discussion/TownOfHost-TheOtherRoles#28]
Crash when using vulture and mare and Marksman professions
When multiple people install the mod and start the game, all players will win directly. If the multi-player installs the mod, it will sometimes get stuck and cannot start the game.
Neutral occupations with more than three crew members will win directly
The above bug is obtained by my friend in the actual test

**Comment by music-discussion** [comment]
this is exactly why you don't join a TOH when multiple have same version. While I did add minimum support for it, it barely works. You can sometimes see other's roles in meetings.
