### ISSUE TITLE
Please Release a New Version! :-)

### ISSUE THREAD

**Issue by Gurge44** [music-discussion/TownOfHost-TheOtherRoles#29]
I've seen that you've been working on this mod all day, adding many new roles, and fixing many issues. So, can you please do a pre-release of 0.7b or 0.8b? I'm too excited to wait... :-D

**Comment by Gurge44** [comment]
I don't care if the new pre-release still has bugs and unfinished stuff, I just want to have the new roles :-D

**Comment by P0W3R-0UT4GE** [comment]
I agree with this too. Especially a version containing the Guesser roles, which are pivotal to the gameplay imo.

**Comment by Gurge44** [comment]
Same, I mainly want the Guesser roles too

**Comment by SkullCreeper** [comment]
We're working on it :)
We're currently on dev 3 last time I checked.
We can't release an alpha version as there are major bugs that must be fixed, such as Marksman banning the host after they get three kills (kill distance becomes invalid).
As for the release of v0.7b, not sure why Discussions has not released that version.

Would've replied earlier but I was asleep :P

**Comment by Tommy-XL** [comment]
What I really want is version 0.7b with guessing roles at least, and Marksman can be turned off for now and fixed in the future

**Comment by P0W3R-0UT4GE** [comment]
Me as well. If 0.7b seems ready to be public, do you know about when we could expect it to be released SkullCreeper?

**Comment by McNnane** [comment]
Does .7b include guessing roles? Also, what dev do you need to get to before alpha would be ready, out of curiosity

**Comment by SkullCreeper** [comment]
I have no idea when 0.7b releases, as the last dev version for it was dev 9.55.
I'm not sure if Assassin, Vigilante, or Pirate are in 0.7b. They were in the dev versions so they might.

**Comment by MrDonkus** [comment]
If you guys look at the mediafire link at the top of the .7a release you would see that it is .7b.
Either way im still running on .6.3b release cause its so much less buggy.
I personally would rather have a more stable mod so ill happily wait until a less buggy version comes out.

**Comment by Gurge44** [comment]
Question: How can you download dev versions if this mod and make it work?

**Comment by music-discussion** [comment]
v0.8b is coming shortly =)
