### ISSUE TITLE
Latest modifier push update!

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#30]
Flash, Oblivious,Torch gives host a black screen!
Investigator button does not work!/edit for host!
Host keeps losing chat during meetings (happens a lot since 0.7b)

**Comment by music-discussion** [comment]
Yea the modifiers are fixed. The reason host keeps losing chat is due to players leaving. And, I haven't been Investigator but try opening map and closing it. See if that helps.

**Comment by iChlorox** [comment]
Bait modifier does not self-report (dev4 update testing onwards)

**Comment by iChlorox** [comment]
![image](https://user-images.githubusercontent.com/91646808/189049446-2efb24e9-95e5-4560-8d8e-8f04664fdc1c.png)
Sleuth modifier doesnt show anything (I was impostor + sleuth, self reported and couldn't see the role)
![image](https://user-images.githubusercontent.com/91646808/189049531-a25b4925-0fd2-4e24-93a6-b16e2acb8f93.png)

**Comment by iChlorox** [comment]
![image](https://user-images.githubusercontent.com/91646808/189079866-8f54ab88-6589-43a5-aa68-5350b4c0c1de.png)
![image](https://user-images.githubusercontent.com/91646808/189079931-18a4b9b6-7eec-4402-8bcb-fc13995f66a2.png)
Blood knight also not visible on snitch

**Comment by SkullCreeper** [comment]
Pretty sure Snitch seeing neutrals (and Coven) is a setting

**Comment by music-discussion** [comment]
yea it is a setting. did you have it on?

**Comment by MrDonkus** [comment]
Also Sleuth information is shown in the chat box not next to player names.

**Comment by iChlorox** [comment]
I had all snitch settings enabled.

![image](https://user-images.githubusercontent.com/91646808/189169925-9dd018cd-a417-4388-aeaa-ffb82a8d6534.png)

**Comment by iChlorox** [comment]
Dead impostors disconnecting ruin the game for alive neutrals btw

**Comment by music-discussion** [comment]
I know. Without impostors, game blackscreens, so thats why I made game insta end if impostors disconnect.

**Comment by iChlorox** [comment]
Isn't there a way around it, like host having an impostor-like modifier, that games reads as impostor and doesn't end if the imps disconnect? i have no idea how to code so i understand if its impossible

**Comment by music-discussion** [comment]
yea sadly no.

**Comment by music-discussion** [comment]
if host is impostor then, game will never black screen, unless you leave.
