### ISSUE TITLE
Question: How to download dev versions??

### ISSUE THREAD

**Issue by Gurge44** [music-discussion/TownOfHost-TheOtherRoles#32]
Question: How can you download dev versions of this mod and make it work?

_Originally posted by @Gurge44 in https://github.com/music-discussion/TownOfHost-TheOtherRoles/issues/29#issuecomment-1240276220_

**Comment by SkullCreeper** [comment]
Discussions sends you one and you load it like any other mod. Otherwise you don't get dev versions.

**Comment by music-discussion** [comment]
or you can just build the current version uploaded on github.
