### ISSUE TITLE
Current state is unbuildable?

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#34]
![image](https://user-images.githubusercontent.com/91646808/189183233-1477b6fb-28ed-4802-9460-3a05fd477a23.png)
I don't know what changed but whatever i was doing is no longer working! 
Previous versions build fine even if they give unreachable code errors
![image](https://user-images.githubusercontent.com/91646808/189184398-3c087fbf-bd5a-452a-be82-577d1518b0cc.png)

**Comment by iChlorox** [comment]
It was this line that made it un-buildable: 
on mudules>Utils>297 line
if (cp.Data.IsDead) continue;

**Comment by music-discussion** [comment]
sorry i know why

**Comment by music-discussion** [comment]
its fixed. try again

**Comment by iChlorox** [comment]
Thank you, btw where do people can find your discord? i cant find it anywhere

**Comment by iChlorox** [comment]
Works now!

**Comment by Tommy-XL** [comment]
How do you compile the mod?  Is there a video guide somewhere on how to do this?

**Comment by MC-AS-Huier** [comment]
> 你如何编译模组？是否有关于如何执行此操作的视频指南？

In fact, it is very simple, just install a .Net and set a variable named AmongUs variable to the game folder where Bepinex has been installed, and then open CMD in the folder of the file with the .csproj suffix and enter dotnet build. For details, please refer to the content of this URL docs.reactor.gg

**Comment by Tommy-XL** [comment]
For some reason I can't do it, a lot of errors come out

![image](https://user-images.githubusercontent.com/104814436/189342378-719ffab3-3a0c-4db7-8045-a2b36437e411.png)

**Comment by Tommy-XL** [comment]
I installed .Net but without success, the same thing pops up

**Comment by Tommy-XL** [comment]
Okey :(
