### ISSUE TITLE
Coven

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#35]
Necromancer does not spawn and sheriff does not seem to work when Coven is enabled (Invalid)  on bullets!
![image](https://user-images.githubusercontent.com/91646808/189236351-e3718831-71c0-41e4-88ce-74a3dba567ac.png)
Also coven always gives witch, but not the other roles .

And i can't pinpoint what role gives blackscreen with coven but i'll show you the preset i used for it and i always got blackscreen!
![image](https://user-images.githubusercontent.com/91646808/189241716-27826148-5f54-4429-b060-22cc997859fe.png)
![image](https://user-images.githubusercontent.com/91646808/189241730-870345b3-83c6-4ce0-a6ce-263c01dd4ef2.png)
![image](https://user-images.githubusercontent.com/91646808/189241741-8c0e870c-921f-46b3-a018-d34c58834352.png)
![image](https://user-images.githubusercontent.com/91646808/189241751-fa667b6b-ec05-46f8-9cb6-ed5bbb5f675d.png)
![image](https://user-images.githubusercontent.com/91646808/189241759-6d9b8ccc-8dd2-4dc6-aa78-73f43cc96365.png)
![image](https://user-images.githubusercontent.com/91646808/189241767-f0a61c6d-a858-449f-aa30-ea83aba0718f.png)
![image](https://user-images.githubusercontent.com/91646808/189241780-9c2b7335-6846-4d19-948f-d28bb274a2d2.png)
![image](https://user-images.githubusercontent.com/91646808/189241802-aca54b83-3be8-4662-b16e-3b330e5c5ab6.png)
![image](https://user-images.githubusercontent.com/91646808/189241820-0d138900-da01-4d33-b7aa-e968f3a2ae98.png)
![image](https://user-images.githubusercontent.com/91646808/189241838-c341645f-027b-47a0-8ced-502f76a26516.png)
![image](https://user-images.githubusercontent.com/91646808/189241853-bdc7357c-4a57-4446-ab99-b26d7cd4460a.png)
![image](https://user-images.githubusercontent.com/91646808/189241870-40b853d2-90aa-427f-9a0d-5fe750985049.png)
![image](https://user-images.githubusercontent.com/91646808/189241884-f9d01aa0-d4e8-44f9-804f-1bd429e5f7ca.png)
![image](https://user-images.githubusercontent.com/91646808/189241894-bed8665b-e0a7-4098-955b-26add4850ceb.png)
![image](https://user-images.githubusercontent.com/91646808/189241914-3dc69a59-943e-4ec8-95b7-f51adf50d257.png)
![image](https://user-images.githubusercontent.com/91646808/189241924-31eca639-c560-48e2-8883-c843dfc63c1e.png)
![image](https://user-images.githubusercontent.com/91646808/189241933-2bce2704-f862-4844-b575-8d7d391b378d.png)

If im doing something wrong in setting it up sorry for opening the issue but i get blackscreened every time

**Comment by music-discussion** [comment]
The only working Coven Roles currently are Hex Master, Medusa, Leader, and Poisoner.

**Comment by music-discussion** [comment]
also the min/max settings currently are just for show. they dont work
