### ISSUE TITLE
Not working command

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#37]
/n /l command not working on bc90eb2  and when i start the game it instantly gives a crew win!

**Comment by music-discussion** [comment]
what roles do you have on

**Comment by iChlorox** [comment]
The new ones i switched back to the previous version now but i added like all of the new ones

**Comment by iChlorox** [comment]
Do you have a discord server for the mod, maybe to be more reachable?

**Comment by music-discussion** [comment]
try 0.8b? And see if it still happens

**Comment by iChlorox** [comment]
I'm currently on a3af0db7015db69d5972c7a17cd48845f5244300 and it works fine

**Comment by iChlorox** [comment]
yes.. YES IT DOES IT on 0.8b!
![image](https://user-images.githubusercontent.com/91646808/189256485-f9948957-6bf0-4600-85a6-563aac2abf6e.png)
![image](https://user-images.githubusercontent.com/91646808/189256494-1940f803-7bb5-4040-9aa3-86158d179822.png)
![image](https://user-images.githubusercontent.com/91646808/189256504-310ec18f-c37c-4167-9f2e-771eee36524a.png)
![image](https://user-images.githubusercontent.com/91646808/189256520-dccdeb0d-eef1-4fa9-9bed-415b6c3be04b.png)
![image](https://user-images.githubusercontent.com/91646808/189256538-3a579ead-cedd-411a-8646-58f1e0929297.png)
![image](https://user-images.githubusercontent.com/91646808/189256546-1c578cc3-8037-4a7e-b911-3a1901464288.png)
![image](https://user-images.githubusercontent.com/91646808/189256562-cffba284-7755-40e1-bae4-cbc69c9da4ce.png)
![image](https://user-images.githubusercontent.com/91646808/189256577-942f4422-43d4-49ed-b618-aa538bc39618.png)
![image](https://user-images.githubusercontent.com/91646808/189256596-10315d72-de66-4251-a88d-ce5a333be0fc.png)
![image](https://user-images.githubusercontent.com/91646808/189256615-e22f1c6b-34e4-461f-870c-50bd4edfe12a.png)
![image](https://user-images.githubusercontent.com/91646808/189256637-f8d2f7c0-e09f-4187-940d-f12c62ec5dc1.png)
![image](https://user-images.githubusercontent.com/91646808/189256658-c7b3f0a9-bd91-4a29-a69c-1ec57f72da5d.png)
![image](https://user-images.githubusercontent.com/91646808/189256676-e737f23d-e01b-4567-822e-5c81d117594b.png)
![image](https://user-images.githubusercontent.com/91646808/189256693-8a28c31f-4856-4f5f-b79a-24a1101f1d9f.png)

**Comment by BornBasic** [comment]
command /n , /n r, /l is not working (as a host) on Toh Tor v0.8b

**Comment by iChlorox** [comment]
Removed Serial killer and done it,
Removed Serial killer and Mercenary, and done it again!
Removed Serial killer and mercenary and Crewpostor and it still done it!
Removed ALL Roles and it still done it! 
That's not a role issue!

**Comment by iChlorox** [comment]
I enabled "No Game End" and it just stayed in this loading screen forever
![image](https://user-images.githubusercontent.com/91646808/189257235-75c2ec5d-4379-444e-9d79-ce2e70273e7a.png)

**Comment by music-discussion** [comment]
also Serial Killer is just renamed Jackal.

**Comment by iChlorox** [comment]
Yeah i noticed and Mercenary is renamed Serial killer, is it fixed? what was it

**Comment by iChlorox** [comment]
![image](https://user-images.githubusercontent.com/91646808/189425353-8d15522e-087c-43da-98c9-6a5d23286508.png)
If it helps every game just does this..
