### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by soukunsandesu** [music-discussion/TownOfHost-TheOtherRoles#41]
Why our Guesser added without credit?

**Comment by SkullCreeper** [comment]
I added credit just now for the original Town Of Host mod and its pull requests.

**Comment by music-discussion** [comment]
ur friend wants them removed anyways soooooooooooooooooooo

**Comment by P0W3R-0UT4GE** [comment]
Please do not remove Guesser roles. Credit should be good enough and the released ToH mod does not include them anyway

**Comment by soukunsandesu** [comment]
He will add in the next version...

**Comment by soukunsandesu** [comment]
Original TOH developer want you to remove guesser.

**Comment by Tommy-XL** [comment]
And this mod will then remain without guessing roles? This is strange....

**Comment by McNnane** [comment]
Is guesser unique to ToH? Doesn’t it come from ToR?

**Comment by P0W3R-0UT4GE** [comment]
Yes, it's in both ToU and ToR, so I don't see what the issue is here. It's not like the ToH devs created the role or even the idea for the role.

**Comment by music-discussion** [comment]
if you are going to tell me to remove Guesser, why also ask me why I added Guesser??????????? like the point?

**Comment by music-discussion** [comment]
what if I bring back guessers and such when official TOH releases them.

**Comment by soukunsandesu** [comment]
> and what if I bring back guessers and such when official TOH releases them.

No problem

**Comment by soukunsandesu** [comment]
> Yes, it's in both ToU and ToR, so I don't see what the issue is here. It's not like the ToH devs created the role or even the idea for the role.

see SourceCode
![image](https://user-images.githubusercontent.com/76250388/189470644-3807342a-51cd-4d89-a8eb-87bc172072cf.png)
たんぽぽ is Original TOH Develoer.

**Comment by soukunsandesu** [comment]
https://github.com/music-discussion/TownOfHost-TheOtherRoles/blob/main/Roles/Ninja.cs
This code is our code, right?

**Comment by yurinakira** [comment]
About why Mr. Sou-kun says "Please turn it off".

This is because TOHTOR uses the code of the role that is in the process of being created and has not been released on TOH without permission.

**Comment by yurinakira** [comment]
"Gesser" and "Ninja" are under development in development version. Since you are using the code without permission,
Creators feel "stole unreleased code".

**Comment by music-discussion** [comment]
If you really want to go that deep, where did the idea of guesser and ninja come from ?

**Comment by yurinakira** [comment]
It's not about ideas, it's about code.

**Comment by soukunsandesu** [comment]
These role idea come from The Other Roles.
But, we put credit.
Violation of GPLv3's license.

**Comment by music-discussion** [comment]
I don’t really understand licensing and stuff because it’s GitHub. :/
For licensing just don’t make the source code public :/

**Comment by music-discussion** [comment]
And plus I didn’t just directly steal your code. I modified it and changed it.

**Comment by W1GZY** [comment]
> These role idea come from The Other Roles. But, we put credit. Violation of GPLv3's license.

There is no violation of GPL v3 licence here. 
- You have a code you have released public under licence of GLP v3.
- Everyone is allowed to use, edit or change the code under the same licence.
- Music-discussion is using the code (that is still public) without charging anyone.
- The changed code is public. 

Where is the violation??

- Mek

**Comment by soukunsandesu** [comment]
OK.
I understand it.
