### ISSUE TITLE
Disconnecting once game starts

### ISSUE THREAD

**Issue by Shredded5** [music-discussion/TownOfHost-TheOtherRoles#45]
Everytime I try to play with the mod I load it and get a role and immediately after it just crashes. 
Been trying to download the v.8.2.2b but doesn't want to download. Followed https://www.youtube.com/watch?v=yBVShYjQdE8&t=0s&ab_channel=AnonWorks Tried unistalling and reinstalling it with a fresh folder and Im stuck
Build number is 2267  v.0.7b.

**Comment by SkullCreeper** [comment]
What error are you getting?

**Comment by Tommy-XL** [comment]
Make sure Lover is not enabled

**Comment by music-discussion** [comment]
You are on an old version

**Comment by Eeveefan302** [comment]
Make sure to be on 0.8.2.2b or 0.8b and above, otherwise you're gonna crash, trust me, i know.

**Comment by Shredded5** [comment]
Have no idea what I did but just did a clean install of both and it seems to be working. Have my thanks on assisting in my mess to correct it.

**Comment by kucingmalas** [comment]
have u tried changing server?

**Comment by Shredded5** [comment]
> have u tried changing server?
That seems to temporally solve the problem but I'll take what I can get to get non crashed games.
