### ISSUE TITLE
Problem with cooldown Warlock, ninja... etc

### ISSUE THREAD

**Issue by aphter** [music-discussion/TownOfHost-TheOtherRoles#46]
In among us settings, impostor's cooldown is 30, but, when I host, sometimes people tell me that the cooldown is up to like 60, and I have no idea if it's a bug or how can I fix it. I happens with warlock, ninja, timethief, vampire, and I don't remember what else

**Comment by W1GZY** [comment]
Developers are aware of this bug and are looking into it.
