### ISSUE TITLE
Disconnect bug

### ISSUE THREAD

**Issue by Gurge44** [music-discussion/TownOfHost-TheOtherRoles#48]
Log: [LogOutput.log](https://github.com/music-discussion/TownOfHost-TheOtherRoles/files/9540028/LogOutput.log)
Video: https://youtu.be/HRZ1JrTw_IQ
It has happened every time when someone joined the game (about 3 seconds after), and only since the latest update. I tried reinstalling twice and the problem did not resolve. I am on v0.8.2.2b
Please tell me what I did wrong

**Comment by Gurge44** [comment]
So, did you solve the problem? Will in not happen in the next update?

**Comment by music-discussion** [comment]
nope. the log gives no info whatsoever. and TSC says its just a packet issue
