### ISSUE TITLE
Chat bug ingame

### ISSUE THREAD

**Issue by slfsen** [music-discussion/TownOfHost-TheOtherRoles#49]
During the game sometimes i cant use chat, like the chat bubble is gone.

**Comment by SkullCreeper** [comment]
This is a well known bug and we're still working on trying to find a fix for it.
We know where in the code that causes it, but we don't know why it happens.

**Comment by Gurge44** [comment]
The known bug description says:
That happens only to host, and only when players leave during the game. Commands are also not available while the chat is gone.
