### ISSUE TITLE
Screen Blacked

### ISSUE THREAD

**Issue by slfsen** [music-discussion/TownOfHost-TheOtherRoles#51]
I cant play because screen is black.
![balck](https://user-images.githubusercontent.com/113254202/189493563-c31ee814-df45-4610-89ad-8680eb53733d.png)

**Comment by music-discussion** [comment]
Specific conditions have to be met for this to happen. 1 of those are if anyone leaves during role announcement sceeen.

**Comment by slfsen** [comment]
People love leaving at the start for no reason

**Comment by slfsen** [comment]
no one left and it still happened

**Comment by music-discussion** [comment]
what roles are on ?

**Comment by iChlorox** [comment]
Are Lovers on? it does that with Lovers

**Comment by slfsen** [comment]
Lovers are off.

**Comment by W1GZY** [comment]
Turn of Terrorist and retry

**Comment by slfsen** [comment]
OK

**Comment by slfsen** [comment]
Terrorist was already off

**Comment by W1GZY** [comment]
> what roles are on ?

Are you able to post a list of the roles you are using

**Comment by slfsen** [comment]
yes

**Comment by slfsen** [comment]
Witch
Assasin
Pirate
Demonlitionist
Bastion
Veteran
Mayor
Sabotagemaster
Investigator
Snitch
Medium 
Doctor
Jester
Survivor
Executioner
Coven
Vulture
Torch 
Bait

**Comment by music-discussion** [comment]
which coven roles?

**Comment by slfsen** [comment]
poison master

**Comment by music-discussion** [comment]
potion master is not done yet. please take it off.

**Comment by slfsen** [comment]
ok

**Comment by slfsen** [comment]
Thank you it finally works.
