### ISSUE TITLE
The auto-win bug is back e60bece

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#52]
![image](https://user-images.githubusercontent.com/91646808/189500452-bed42eae-2b4d-440b-8029-63422a61e2e0.png)
Just downloaded [e60bece](https://github.com/music-discussion/TownOfHost-TheOtherRoles/commit/e60bece988402f8d8f0fdec94bf87fb8ac2f330a) and the auto-win is back (fix blackscreen again)

**Comment by SkullCreeper** [comment]
Well its a WIP, this is expected :P

**Comment by music-discussion** [comment]
thats weird because I literally just tested it and it works fine. but what TSC said is true.
