### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by Shredded5** [music-discussion/TownOfHost-TheOtherRoles#54]
When being alive or dead the text blends into the name and becomes unavailable to read. Way to fix this issue?

**Comment by music-discussion** [comment]
In latest update we have something to combat it, using SHIFT+C+ENTER will force chat to be visible.

**Comment by Shredded5** [comment]
> In latest update we have something to combat it, using SHIFT+C+ENTER will force chat to be visible

That was a quick response. Thank you
