### ISSUE TITLE
Packet Error issue

### ISSUE THREAD

**Issue by ViesSPR** [music-discussion/TownOfHost-TheOtherRoles#57]
Since 0.8.3: Packet error as soon as someone joins the lobby. Have tried it with all the settings turned to 0% too.
Since 0.8.2 Packet error when starting about every ~3rd game
0.7 and Before those versions: No packet error issues
Internet speed isn't(or shouldn't) be an issue for this one. Ive got 100mbps download and 50mbps upload.
[Player.log](https://github.com/music-discussion/TownOfHost-TheOtherRoles/files/9543632/Player.log)
![Screenshot_3](https://user-images.githubusercontent.com/113314808/189551118-f53c3897-c5fd-480b-b62d-8e188c6b053c.png)

**Comment by Gurge44** [comment]
I have the same issue and sadly neither me or any of the devs know what is causing this issue. The way I processed it is: "I simply got unlucky to be one of the few people who experience this bug while others can play with no problems and no one can help me solve this because no one has any idea how to reproduce this." I installed TOH-TOR on another PC and this bug was nowhere to be found. So the only fix I can imagine is...... **reinstall windows**

**Comment by ViesSPR** [comment]
I've been trying hard to get it work, so this is what i've done so far:
Completely wiped all the Among us Data in:
C:\Program Files (x86)\Steam\steamapps\common\Among Us
C:\Users\Viest\AppData\LocalLow\Innersloth\Among Us
Result: same issue
Completely reinstalled Steam, including wiping all the cache folders from Appdata.
Result: same issue
Tried installing TOHTOR 0.8.3.1b in the same directory where Among Us lays(in the steamapps, used to do a seperate directory like in the videos, where you copy Among us file in seperate folder)
Result: same issue.

So far i havent managed to get it to work on my PC. I tried on my other laptop, which is almost the same specs wise, and i do not get this issue on the same network.

**Comment by ViesSPR** [comment]
Aaaaaaaand, now i have managed to get it to work. Literally not even later than 10 minutes before previous post. Note that ive been fighting with this issue for 2 days now.

For some reason, when im on Ethernet cable, i get the packet error issue. When i switch to WiFi, the issue seems to not exist. Any help on why this would cause the issue would be appreciated. I tried updating my Ethernet drivers already, and completely reinstalling them too. Nothing changes.

**Comment by larushco** [comment]
Try changing the server (North America, Europe, etc. in the bottom right corner of the starting screen).

You might be on a custom server.

**Comment by ViesSPR** [comment]
That wasn’t really the cause for me.
Some people in Discord, however, have mentioned that VPN currently fixes this issue for some.
