### ISSUE TITLE
Coven is broken

### ISSUE THREAD

**Issue by DarkFedora64** [music-discussion/TownOfHost-TheOtherRoles#64]
The Coven are just nonexistent eve when I turn them on, They are as nonexsistent as my happiness at school

But seriously Coven don't work

**Comment by SkullCreeper** [comment]
Coven does work...? Make sure Coven Leader, Medusa, and Hex Master are on :P

![Screenshot 2022-09-05 12 50 09 AM](https://user-images.githubusercontent.com/51543683/189752992-9b20cb24-ffa9-40a8-9737-1bc617d8bb1b.png)
