### ISSUE TITLE
Host still sees roles in meetings/NK roles break game/pirate doesn't work/

### ISSUE THREAD

**Issue by Kpibb78** [music-discussion/TownOfHost-TheOtherRoles#65]
In both 0.8.3.1-0.8.3.1b I can still see the person's role next to me, it goes away after death.
When plaguebearer or glitch is alive after imps die, console players get black screen. 
I know these are stated in notes, but the only roles that really work are from 0.7.0. 
Pirate is just killing role no guessing

I love the modifiers though. That's a great idea

**Comment by music-discussion** [comment]
Console games already lag a lot. Console is currently not optimised. How the game prevents blackscreens is not compatible. The bug for seeing other’s roles has been fixed.
