### ISSUE TITLE
Role Suggestion: Ninja

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-TheOtherRoles#7]
(I used a translator when writing the text, there may be errors)

Role: Ninja
Impostor (Shapeshifter)

His role will be similar to the role from the "TheOtherRoles" mod.
He can kill players wherever they are, for this they need to mark the target with the "Kill" button and after that they need to press SHIFT, once they are ready to teleport to the player they must press the SHIFT button again, after that they kill the marked target and teleport to him

(I don't know if it is possible to implement this in this mod, but I think it is possible, and on GitHub TownOfHost there is already an open source code for the Ninja role)

**Comment by music-discussion** [comment]
In TOR, the ninja is invisible. We cannot make the Ninja invisible. What do you want to do instead?

**Comment by Tommy-XL** [comment]
Hmm, I may have to refuse to replace it, since in this mod I don’t see a replacement for this yet, I think I’ll have to rely only on luck and only (but there is also a power outage sabotage, it can help the traitor a little so that he is not immediately noticed from  far)

If anyone has any ideas they can write about it below

**Comment by Tommy-XL** [comment]
Although, there is one idea, when he marks his target, he can press the SHIFT button and select any player from the list, and when he changes appearance, he immediately teleports and kills the player, so no one sees his true appearance and when the cooldown passes,  he will return to his form

**Comment by music-discussion** [comment]
Huh, alright.

**Comment by music-discussion** [comment]
Ninja was added.
