### ISSUE TITLE
Role idea:Eraser

### ISSUE THREAD

**Issue by Duckposter** [music-discussion/TownOfHost-TheOtherRoles#71]
Team:Impostor
Basis:ShapeShifter
so this mod can change ur role on game but what about DELETE roles on game? this role can make imp game more easy but he can't kill when make it
on ShapeShifter form eraser can't kill but can erase player role (if he hit Crew role change on Crewmate if Neu evil or binign on Opportunist(not surv) if NK on Serial Killer) if not on ShapeShifter form he just a simple impostor
Settings^
Eraser kill cd
Eraser erase cd
Limit of Erases 1 - 15

**Comment by music-discussion** [comment]
I think it should work the opposite. Erasing while not shifted. Or just do a switching form like Witch.

**Comment by Duckposter** [comment]
so idea Erase when not Shapeshifter is more good i am agree and i think if he hit any Madmate role he need change it on simple Madmate or just hit on shield(without erase player role)
