### ISSUE TITLE
Some questions about translation.

### ISSUE THREAD

**Issue by xiaojinna** [music-discussion/TownOfHost-TheOtherRoles#76]
Hi Author, I see that the translation I fixed with the translated SChinese content has not been passed, is there something wrong with it?

**Comment by W1GZY** [comment]
Looks pretty self explanatory to me. Save your translations string file, update your fork to the latest then change the new string file with the translations from the old string file. Your pull request was just before a big change.

**Comment by xiaojinna** [comment]
> Looks pretty self explanatory to me. Save your translations string file, update your fork to the latest then change the new string file with the translations from the old string file. Your pull request was just before a big change.

I did sync the author's library in a recent upload, but it wasn't agreed upon, am I too slow to update?

**Comment by music-discussion** [comment]
its been pushed.
