### ISSUE TITLE
Role Suggestion:Chief

### ISSUE THREAD

**Issue by Duckposter** [music-discussion/TownOfHost-TheOtherRoles#8]
Role:Chief
Basis:Impostor
Victory Condition:kill everyone
Jackal on this mod can't make Sidekick for help. What about alternative? when u press vent first u change role of nearest player on Partner(like Morph change nearest player on SideKickMadmate). Partner can kill with u and changed on Chief when u die(and make another Partner)
Game Optonts
Partner can kill (Yes,No)
Partner killl cd
Chief kill cd
Partner changed on Chief after Chief die(Yes,No)

**Comment by music-discussion** [comment]
We can't change your Among Us role. So they would have to be Impostor or Shapeshifter for them to be able to kill.
