### ISSUE TITLE
Has anyone else died from a puppeted player while GM?

### ISSUE THREAD

**Issue by larushco** [music-discussion/TownOfHost-TheOtherRoles#83]
A crew member was puppetted and I was closest, so I was killed, even though I was a GM ghost.  Not sure if anyone else has experienced this.

**Comment by Gurge44** [comment]
Since GM is only in v0.7b at the moment, and not many people play with Puppeteer, I don't think this coincidence happens often.

**Comment by larushco** [comment]
I just found this interesting.  I had never experienced being killed as a ghost before.

**Comment by music-discussion** [comment]
thanks for letting me know. ill be sure to patch this for 0.8.5
