### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by MC-AS-Huier** [music-discussion/TownOfHost-TheOtherRoles#9]
There is currently a bug that kicks out all players as soon as the Camouflager skill is used

**Comment by Tommy-XL** [comment]
Wait, the role of Camouflage in fashion is already in development?

**Comment by MC-AS-Huier** [comment]
> 等等，伪装在时尚界的作用已经在发展中了吗？
This is the same question as #10, which he told me

**Comment by MC-AS-Huier** [comment]
> Wait, the role of Camouflage in fashion is already in development?
This is the same question as #10, which he told me

**Comment by music-discussion** [comment]
I have noticed. I will look for a solution.
