### ISSUE TITLE
Camouflager bug 0.9.1

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-TheOtherRoles#96]
Camouflage still not working correctly after meeting
But **Nickname** returned to the reverse position, but the appearance itself is not (Purple was Camouflager)

![photo_2022-09-29_20-56-23](https://user-images.githubusercontent.com/104814436/193037629-53146e17-6cfe-4d6a-8e85-e0366b99a5e8.jpg)

**Comment by music-discussion** [comment]
fixed i hope
